--- #YAML:1.0
name:               Data-UUID-Base64URLSafe
version:            0.34
abstract:           URL-safe UUIDs
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::UUID:           0
    MIME::Base64::URLSafe:  0
    Test::More:           0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
